#!/bin/bash

arm-none-eabi-gcc -x assembler-with-cpp -c -O0 -mcpu=cortex-m0 -mthumb -Wall core.S -o core.o

arm-none-eabi-gcc core.o -mcpu=cortex-m0 -mthumb -Wall  --specs=nosys.specs -nostdlib -lgcc -T./STM32L4A6RG_FLASH.ld -o main.elf
